name: Deploy app on stage manual
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-push-image-stage:
    uses: ./.github/workflows/ecr-build-push.yml
    with:
      ecr_repo: ${{ github.event.repository.name }}
      environment: stage
    secrets: inherit
  deploy-eks-stage-manual:
    needs: [build-and-push-image-stage]
    uses: ./.github/workflows/eks-deploy.yml
    with:
      environment: stage-manual
      service_name: ${{ github.event.repository.name }}
      namespace: ${{ github.event.repository.name }}
      clusters: >-
        [
          {"region":"us-east-1", "name":"crypto-stage-us-east-1"}
        ]
    secrets: inherit
