name: Deploy app on stage manual
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build-and-push-image-stage:
    uses: ./.github/workflows/ecr-build-push.yml
    with:
      ecr_repo: ${{ github.event.repository.name }}
      environment: stage
    secrets: inherit
  deploy-eks-stage-manual:
    needs: [build-and-push-image-stage]
    uses: ./.github/workflows/eks-deploy.yml
    with:
      environment: stage-manual
      aws_region: >-
        ["us-east-1"]
      service_name: ${{ github.event.repository.name }}
      namespace: ${{ github.event.repository.name }}
      cluster_name: crypto
    secrets: inherit
