name: Deploy app on stage and prod
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-image-stage:
    uses: ./.github/workflows/ecr-build-push.yml
    with:
      ecr_repo: ${{ github.event.repository.name }}
      environment: stage
    secrets: inherit

  list-stage-clusters:
    runs-on: ubuntu-latest

    needs: [build-and-push-image-stage]
    environment: stage

    permissions:
      id-token: write
      contents: read

    outputs:
      cluster_list: ${{ steps.eks-list-clusters.outputs.cluster_list }}

    steps:
      # We can't use `eks-list-clusters` directly because this repo is public
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3
        with:
          repository: worldcoin/gh-actions
          ref: eks-list-clusters-v1
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/gh-actions
      - name: List EKS clusters
        id: eks-list-clusters
        uses: ./.github/actions/gh-actions/eks-list-clusters
        with:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws_region_list: "us-east-1"
          environment: "stage"

  deploy-eks-stage:
    needs: [list-stage-clusters]
    strategy:
      matrix:
        include: ${{ fromJson(needs.list-stage-clusters.outputs.cluster_list) }}
    uses: ./.github/workflows/eks-deploy.yml
    with:
      environment: stage
      service_name: ${{ github.event.repository.name }}
      namespace: ${{ github.event.repository.name }}
      cluster: ${{ matrix.cluster }}
      region: ${{ matrix.region }}
    secrets: inherit

  build-and-push-image-prod:
    needs: [deploy-eks-stage]
    uses: ./.github/workflows/ecr-build-push.yml
    with:
      ecr_repo: ${{ github.event.repository.name }}
      environment: prod
    secrets: inherit

  list-prod-clusters:
    runs-on: ubuntu-latest

    needs: [build-and-push-image-prod]
    environment: prod

    permissions:
      id-token: write
      contents: read

    outputs:
      cluster_list: ${{ steps.eks-list-clusters.outputs.cluster_list }}

    steps:
      # We can't use `eks-list-clusters` directly because this repo is public
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v3
        with:
          repository: worldcoin/gh-actions
          ref: eks-list-clusters-v1
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: .github/actions/gh-actions
      - name: List EKS clusters
        id: eks-list-clusters
        uses: ./.github/actions/gh-actions/eks-list-clusters
        with:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws_region_list: "us-east-1"
          environment: "prod"

  deploy-eks-prod:
    needs: [list-prod-clusters]
    strategy:
      matrix:
        include: ${{ fromJson(needs.list-prod-clusters.outputs.cluster_list) }}
    uses: ./.github/workflows/eks-deploy.yml
    with:
      environment: prod
      service_name: ${{ github.event.repository.name }}
      namespace: ${{ github.event.repository.name }}
      values_filename: values-prod.yaml
      cluster: ${{ matrix.cluster }}
      region: ${{ matrix.region }}
    secrets: inherit
