name: Build, test and push docker image to ECR

on:
  workflow_call:
    inputs:
      ecr_repo:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build & Push to ECR
        uses: worldcoin/gh-actions/ecr-build-and-push@ecr-build-and-push-v3
        with:
          ecr_repo: ${{ inputs.ecr_repo }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
